### ISSUE TITLE
mailing list link shows a 'Content unavailable' message

### ISSUE THREAD

**Issue by epragalakis** [OWASP/www-chapter-scotland#3]
Is this a permissions issue?
Can only owasp members access that page?

**Comment by slaughterjames** [comment]
Hi there,

Sorry you've run into difficulty.  Everyone should be able to access the link.  I've just now checked https://groups.google.com/a/owasp.org/forum/#!forum/scotland-chapter both logged into Google and not and unauthenticated to GitHub and I've not been able to replicate your particular issue.  Have another go and let us know if it persists and we'll investigate further.

**Comment by epragalakis** [comment]
ahh it might be an issue with my org's permissions!! 
I'll check with a different email!
